Team-HANOI/AI-interviewer

fresh-balancer-322209-32b1fb455c4c.json
:beer:
없음
키값 파일(fresh-balancer-322209-32b1fb455c4c.json)
<br/>
Close #{이슈_번호}
=> chore : Google TTS API 키값 파일(지우지마시오.)

app/build.gradle, app/src/main/java/com/alpaca/app/SecurityConfig.java, app/src/main/java/com/alpaca/app/config/SecurityConfig.java, app/src/main/java/com/alpaca/app/sample/controller/SampleController.java, app/src/main/java/com/alpaca/app/sample/domain/AuthVO.java, app/src/main/java/com/alpaca/app/sample/domain/MemberVO.java, app/src/main/java/com/alpaca/app/sample/mapper/HRMapper.java, app/src/main/java/com/alpaca/app/sample/mapper/MemberMapper.java, app/src/main/java/com/alpaca/app/sample/mapper/TimeMapper.java, app/src/main/java/com/alpaca/app/security/dto/AuthMemberDTO.java, app/src/main/java/com/alpaca/app/security/service/CustomOAuth2UserDetailsService.java, app/src/main/java/com/alpaca/app/security/service/CustomUserDetailsService.java, app/src/main/resources/application-oauth.properties, app/src/main/resources/application.properties, app/src/main/resources/mybatis-mapper/MemberMapper.xml, app/src/main/resources/templates/sample/admin.html, app/src/main/resources/templates/sample/all.html, app/src/main/resources/templates/sample/member.html, app/src/test/java/com/alpaca/app/persistence/HRTest.java, app/src/test/java/com/alpaca/app/persistence/TimeMapperTest.java, app/src/test/java/com/alpaca/app/security/MemberTests.java
스프링 시큐리티를 활용한 기본 로그인, 소셜로그인 기능 구현
스프링 시큐리티를 활용해 소셜로그인 기능을 만들었습니다.
소셜로그인은 자동회원가입되는 상태고, 기본 회원가입은 구현해야 합니다.
커스텀 페이지 적용은 해봐야 아는 거라.,., sample과 시큐리티 패키지를 건드리지 않는 선에서
작업해주세요.
- **권한 문제 때문에 뭐가 안될 수도 있음**
이것저것 해봤는데 안되면 말해주세요 ㅠ ㅠ 해봐야 압니다!
<br/>
Close #3
=> Feature/login 로그인 기능 구현

app/src/main/java/com/alpaca/app/sample/domain/AuthVO.java, app/src/main/java/com/alpaca/app/sample/domain/MemberRole.java, app/src/main/java/com/alpaca/app/sample/domain/MemberVO.java, app/src/main/java/com/alpaca/app/security/service/CustomOAuth2UserDetailsService.java, app/src/main/java/com/alpaca/app/security/service/CustomUserDetailsService.java, app/src/main/resources/mybatis-mapper/MemberMapper.xml, app/src/test/java/com/alpaca/app/security/MemberTests.java
ENUM 자료형으로 변경
실수로 변경될 일이 없도록 String으로 되어있던 회원권한을 enum으로 변경했습니다
MemberRole.java 추가 및 적용
<br/>
Close #34
=> chore : Add MemberRole.java 회원권한 enum 적용

app/build.gradle, app/src/main/java/com/alpaca/app/config/SecurityConfig.java, app/src/main/java/com/alpaca/app/sample/domain/MemberVO.java, app/src/main/java/com/alpaca/app/security/handler/LoginSuccessHandler.java, app/src/main/java/com/alpaca/app/security/service/CustomOAuth2UserDetailsService.java, app/src/main/java/com/alpaca/app/security/service/CustomUserDetailsService.java, app/src/main/resources/application.properties, app/src/main/resources/log4jdbc.log4j2.properties, app/src/main/resources/logback-spring.xml, app/src/main/resources/mybatis-mapper/MemberMapper.xml, app/src/test/java/com/alpaca/app/security/MemberTests.java
로그인 성공시 핸들링하는 클래스 생성, SQL 실행을 확인할 수 있는 로그 설정
이제 에러 찾기 쉽게 실행된 SQL과 결과가 콘솔에 나타납니다(매우 애먹었음)
<br/>
Close #36
=> [Feature/login] LoginSuccessHandler & loh4j2 설정 

resources/document/ssml스펙체크/ssml문법 기본.md
=> chore : ssml기본 문법

app/build.gradle, app/src/main/java/com/alpaca/app/security/service/CustomUserDetailsService.java, app/src/main/resources/mybatis-mapper/MemberMapper.xml, app/src/main/resources/templates/fragments/footer.html, app/src/main/resources/templates/fragments/header.html, app/src/main/resources/templates/index.html, app/src/main/resources/templates/layouts/template.html
타임리프 dialect를 이용한 템플릿 html 추가
html 템플릿 파일을 추가했습니다
<br/>
Close #53
=> Feature/login 타임리프 dialect를 이용한 템플릿 html 추가

app/src/main/java/com/alpaca/app/config/SecurityConfig.java, app/src/main/resources/templates/layouts/template.html
member/** url 접근권한 에 대해시큐리티 config 수정
/member/**
에 대해 MANAGER와 ADMIN도 접근할 수 있도록 수정
/all/**
/member/**로 컨트롤러 URL맵핑해서 화면 연동 진행하시면 됩니다
디비연동까지 sample 패키지 참고 하시면됩니다!
<br/>
Close #57
=> feat : Update SecurityConfig.java

app/src/main/resources/templates/css/main.css, app/src/main/resources/templates/fragments/footer.html, app/src/main/resources/templates/main.html, app/src/main/resources/templates/main_title.html
=> Refactor:Update main.html

app/src/test/java/com/alpaca/app/hy-mapper/Question.xml, app/src/test/java/com/alpaca/app/hy/dao/Alldao.java, app/src/test/java/com/alpaca/app/hy/vo/PgInfo.java
=> Test:hy Test

Team_Project/src/main/webapp/WEB-INF/views/board/recommend.jsp
인터뷰 하부 컨트롤 두번 뜨는 에러 수정 및 package 생성함.
=> update: 인터뷰 하부 컨트롤 두번 뜨는 에러 수정 및 package 생성

Team_Project/src/main/resources/static/js/index.js, Team_Project/src/main/resources/static/js/pop_ups.js, Team_Project/src/main/resources/static/style/recruit_form.css, Team_Project/src/main/webapp/WEB-INF/views/common/popups/popups.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/main.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/recruit.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/result.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/run.jsp, Team_Project/src/main/webapp/WEB-INF/views/main.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/delete.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mentoring.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mentoring_com.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/myarticle.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/profile.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/pwchange.jsp, Team_Project/src/main/webapp/WEB-INF/views/recruit/form.jsp, Team_Project/src/main/webapp/WEB-INF/views/recruit/list.jsp
- 전체 파일 jsp 파일을 생성하여 모든 팝업 관련 jsp 파일을 저장하고 각 페이지에서는 통합된 jsp 팝업 파일 한번만 호출하도록 refactoring을 함.
- 일부화면에서 비밀번호 재설정 팝업 뜨지 않는 오류 수정(코드 누락)
=> refactor: 전체 팝업 jsp 파일 생성 및 팝엄관련 오류 수정

Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java, Team_Project/src/main/java/com/team/interview/service/ReviewService.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java, Team_Project/src/main/java/com/team/interview/vo/FileVO.java, Team_Project/src/main/java/com/team/interview/vo/PageInfo.java, Team_Project/src/main/java/com/team/interview/vo/RCommVO.java, Team_Project/src/main/java/com/team/interview/vo/ReviewVO.java, Team_Project/src/main/resources/mybatis/mappers/review.xml
지영 프로젝트 통합 vo xml dao service
지영 프로젝트 통합 vo xml dao service
Close #84
=> chore: 지영 프로젝트 통합 vo xml dao service

Team_Project/src/main/java/com/team/interview/dao/InterviewDAO.java, Team_Project/src/main/java/com/team/interview/dao/QuestionDAO.java
=> feat : InterviewDAO, QuestionDAO 추가

Team_Project/src/main/java/com/team/interview/vo/InterviewVO.java, Team_Project/src/main/java/com/team/interview/vo/QuestionVO.java
=> feat : interview.vo 업데이트

Team_Project/src/main/resources/mybatis/mappers/interview.xml, Team_Project/src/main/resources/mybatis/mappers/question.xml
=> feat : mybatis.mappes 업데이트

Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/main.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/nomal.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/recruit.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/result.jsp
일반 면접 분기 추가를 위함
:beer:
<br/>
Close #100
=> feat : header.jsp 업데이트

Team_Project/src/main/webapp/WEB-INF/views/interview/run.jsp
=> chore : run.jsp 수정

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java
=> chore : interviewController 수정

Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp
=> refactor:Update total

Team_Project/src/main/java/com/team/interview/controller/BoardController.java, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total_detail.jsp
=> refactor:Update total_detail

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java
=> interviewController 업데이트

Team_Project/src/main/java/com/team/interview/dao/KeywordDAO.java, Team_Project/src/main/java/com/team/interview/service/KeywordService.java, Team_Project/src/main/java/com/team/interview/service/KeywordServiceImpl.java, Team_Project/src/main/java/com/team/interview/vo/KeywordVO.java, Team_Project/src/main/resources/mybatis-config.xml, Team_Project/src/main/resources/mybatis/mappers/keyword.xml, Team_Project/src/main/resources/static/style/interview_normal.css, Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/test.jsp
=> Custommode

Team_Project/src/main/java/com/team/interview/controller/BoardController.java, Team_Project/src/main/java/com/team/interview/dao/QuestionDAO.java, Team_Project/src/main/java/com/team/interview/service/AllService.java, Team_Project/src/main/java/com/team/interview/service/AllServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total_detail.jsp
추천수정렬 추천하기 구현
<br/>
Close #{이슈_번호}
=> feat:추천 기능

Team_Project/src/main/java/com/team/interview/service/AllServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total_detail.jsp
오 저 완성된것같습니다
<br/>
Close #{이슈_번호}
=> refactor:추천순->최신순 오류잡음

Team_Project/build.gradle, Team_Project/src/main/resources/application.properties, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp
=> feat:Update question.xml

Team_Project/src/main/java/com/team/interview/controller/ReviewController.java, Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/service/ReviewService.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/review.xml, Team_Project/src/main/webapp/WEB-INF/views/board/board_common/board_nav.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/modify.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp
review 게시판 수정버튼 완료 / 네비게이션 활성화
Close #142
=> review 게시판 수정버튼 완료 / 네비게이션 활성화

Team_Project/src/main/resources/application.properties
application.properties
DB경로 설명 추가
로컬DB, 공동DB 설정 정보 업데이트
<br/>
=> application.properties

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/java/com/team/interview/dao/QuestionDAO.java, Team_Project/src/main/java/com/team/interview/service/QuestionService.java, Team_Project/src/main/java/com/team/interview/service/QuestionServiceImpl.java, Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/frontEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/nomal.jsp
=> 일반 면접모드 분기 업데이트

Team_Project/build.gradle, Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/resources/application.properties
공동DB오류, 로컬 DB접속, interviewController 수정
<br/>
Close #{이슈_번호}
=> 공동DB오류, 로컬 DB접속, interviewController 수정

Team_Project/src/main/resources/mybatis/mappers/question.xml
=> frontEnd 질문 기록 버그 해결

Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/frontEnd.jsp
=> result페이지 이동

Team_Project/src/main/java/com/team/interview/config/SecurityConfig.java, Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java, Team_Project/src/main/resources/static/js/board_detail.js, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/write.jsp
[feature/login_board] 면접후기게시판 로그인 연동 기능을 구현한다
- 게시판 목록에서는 글쓰기버튼과 임시저장버튼은 로그인 중인 사용자만 보이게 한다
- 게시판 상세 조회에서는 게시글 수정/삭제 버튼과 댓글 수정/삭제 버튼이 해당 글쓴이가 로그인 중일때만 보이게 한다
Close #158
=> board_review 면접후기게시판 로그인 연동 완료

Team_Project/src/main/java/com/team/interview/dao/InterviewDAO.java, Team_Project/src/main/java/com/team/interview/service/InterviewService.java, Team_Project/src/main/java/com/team/interview/service/InterviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/mentormode.xml, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp
일단 틀을 잡아보고 있숩니다.
<br/>
Close #{이슈_번호}
=> feat:Update mentormode

Team_Project/src/main/resources/application.properties, Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/frontEnd.jsp
=> 면접기록 버그 고침

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/java/com/team/interview/dao/InterviewDAO.java, Team_Project/src/main/java/com/team/interview/service/InterviewService.java, Team_Project/src/main/java/com/team/interview/service/InterviewServiceImpl.java, Team_Project/src/main/java/com/team/interview/vo/MentormodeVO.java, Team_Project/src/main/resources/mybatis-config.xml, Team_Project/src/main/resources/mybatis/mappers/mentormode.xml, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp
=> feat:멘토모드 구현

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/java/com/team/interview/dao/QuestionDAO.java, Team_Project/src/main/java/com/team/interview/service/QuestionService.java, Team_Project/src/main/java/com/team/interview/service/QuestionServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/customMode.jsp
customMode update
<br/>
Close #170
=> customMode update

Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mentoring_com.jsp
멘토입장에서 데이터 보는거 가져오는거 하나만 보이던거
수정 했습니다
<br/>
Close #{이슈_번호}
=> feat:Update mypage

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/java/com/team/interview/dao/InterviewDAO.java, Team_Project/src/main/java/com/team/interview/service/InterviewService.java, Team_Project/src/main/java/com/team/interview/service/InterviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/mentormode.xml, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp
허하하ㅏ 뷰는 나중에 고치는걸로...
<br/>
Close #{이슈_번호}
=> feat:멘토링 신청받기

Team_Project/src/main/resources/static/style/interview_keyword.css, Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp
=> interview_keyword.css 수정

Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/customMode.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/frontEnd.jsp
interview_lastpage update
<br/>
Close #181
=> interview lastpage update

Team_Project/src/main/resources/static/style/board_comment.css, Team_Project/src/main/resources/static/style/board_detail2.css, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail2.jsp, Team_Project/src/main/webapp/board_detail2.css
refactor: board detail front ver1
refactor: board detail front ver1
Close #{이슈_번호}
=> refactor: board detail front ver1

Team_Project/src/main/java/com/team/interview/controller/ReviewController.java, Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java, Team_Project/src/main/java/com/team/interview/service/ReviewService.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/review.xml, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
feat: 게시판 본글 댓글 삭제기능 코드완료
feat: 게시판 본글 댓글 삭제기능 코드완료
Close #{이슈_번호}
=> feat: 게시판 본글 댓글 삭제기능 코드완료

Team_Project/src/main/resources/application.properties
refactor: 통합서버 application properties 경로 수정
refactor: 통합서버 application properties 경로 수정
Close #{이슈_번호}
=> refactor: 통합서버 application properties 경로 수정

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/java/com/team/interview/service/InterviewService.java, Team_Project/src/main/resources/application.properties, Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/customMode.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/main.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/recruit.jsp
recruit모드 업데이트 + custom모드 버그 해결
:beer:
전체 테스트 완료
<br/>
Close #183
=> recruit모드 업데이트 + custom모드 버그 해결

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java
=> feat: Update InterviewController

Team_Project/src/main/java/com/team/interview/controller/ReviewController.java, Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java, Team_Project/src/main/java/com/team/interview/service/ReviewService.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/review.xml, Team_Project/src/main/resources/static/js/board_detail.js, Team_Project/src/main/resources/static/style/board_comment.css, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Feat/comm 대댓글 기능 코드 완성
Feat/comm 대댓글 기능 코드 완성
Close #{이슈_번호}
=> Feat/comm 대댓글 기능 코드 완성

Team_Project/src/main/resources/mybatis/mappers/question.xml
=> 질문 갯수 설정 업데이트

Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp
customMode, recruitMode
회사별모드 : 키워드가 null인 공고 db에서 삭제
맞춤모드 : 키워드 선택 안하면 페이지 안넘어가게
<br/>
Close #193
=> customMode, recruitMode 키워드 선택 버그 수정

Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp
=> feat:Update mentor.jsp

Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java, Team_Project/src/main/java/com/team/interview/service/ReviewService.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/review.xml, Team_Project/src/main/resources/static/style/board_comment.css, Team_Project/src/main/resources/static/style/board_detail2.css, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
refactor: 게시판 이전글 다음글 에러코드 수정 및 프론트 디테일 수정
refactor: 게시판 이전글 다음글 에러코드 수정 및 프론트 디테일 수정
=> refactor: 게시판 이전글 다음글 에러코드 수정 및 프론트 디테일 수정

Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java, Team_Project/src/main/java/com/team/interview/service/ReviewService.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/review.xml, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp, Team_Project/src/main/webapp/board_detail2.css
refactor: 보드삭제 기능 에러 코드 수정
refactor: 보드삭제 기능 에러 코드 수정
Close #{이슈_번호}
=> refactor: 보드삭제 기능 에러 코드 수정

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp
=> normal.jsp 업데이트

Team_Project/src/main/resources/static/js/board_detail.js, Team_Project/src/main/resources/static/style/board_comment.css, Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/review2.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/recruit.jsp
feat: 답글달기 버튼 클릭시 박스나타나기 기능 코드 완료
feat: 답글달기 버튼 클릭시 박스나타나기 기능 코드 완료
광진님 최고
Close #{이슈_번호}
=> feat: 답글달기 버튼 클릭시 박스나타나기 기능 코드 완료 (광진님 최고)

Team_Project/src/main/java/com/team/interview/controller/MainController.java, Team_Project/src/main/webapp/WEB-INF/views/common/nav.jsp, Team_Project/src/main/webapp/WEB-INF/views/common/nav_main.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/main.jsp
=> chore: 지난 병합시 빠진 페이지 연결

Team_Project/src/main/resources/application.properties, Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp
=> View frontt

Team_Project/src/main/java/com/team/interview/controller/MainController.java, Team_Project/src/main/java/com/team/interview/controller/MyPageController.java, Team_Project/src/main/java/com/team/interview/service/ProfileServiceImpl.java, Team_Project/src/main/java/com/team/interview/vo/Criteria.java, Team_Project/src/main/resources/mybatis/mappers/interviewRecord.xml, Team_Project/src/main/webapp/WEB-INF/views/common/nav_main.jsp, Team_Project/src/main/webapp/WEB-INF/views/common/top_t.jsp, Team_Project/src/main/webapp/WEB-INF/views/member/join_com.jsp, Team_Project/src/main/webapp/WEB-INF/views/member/join_com_b.jsp, Team_Project/src/main/webapp/WEB-INF/views/member/join_indv.jsp, Team_Project/src/main/webapp/WEB-INF/views/member/join_indv_b.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mentoring.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mentoring_com.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mypage_common/mypage_nav.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/profile.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/profile_edit.jsp, Team_Project/src/main/webapp/WEB-INF/views/recruit/template.jsp, Team_Project/src/main/webapp/WEB-INF/views/security/userLogin.jsp, Team_Project/src/test/java/com/team/interview/test/ProfileTests.java
=> chore: 잔디 스타일 수정

Team_Project/src/main/resources/static/js/board_detail.js, Team_Project/src/main/resources/static/style/board_comment.css, Team_Project/src/main/resources/static/style/board_detail2.css, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
chore : 보드 프론트 정리
chore : 보드 프론트 정리
Close #{이슈_번호}
=> chore : 보드 프론트 정리

Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/frontEnd.jsp
pos update
<br/>
Close #{이슈_번호}
=> pos update

Team_Project/src/main/java/com/team/interview/controller/BoardController.java, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp
자잘한 수정
페이지 이동시 사이드 메뉴 안나오는거 수정 해야됨
<br/>
Close #{이슈_번호}
=> total.jsp 업데이트

Team_Project/src/main/java/com/team/interview/controller/BoardController.java
boardController update
사이드 메뉴 오류 수정
<br/>
=> boardController update

Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp
checkbox, button update
<br/>
Close #{이슈_번호}
=> cutstom.jsp

Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/mypage_common/mypage_nav.jsp, Team_Project/src/main/webapp/WEB-INF/views/mypage/profile.jsp
=> chore: 마이페이지 스타일 변경

Team_Project/src/main/resources/static/style/board_write.css, Team_Project/src/main/webapp/WEB-INF/views/board/modify.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/write.jsp
refactor : 면접후기 게시판 글쓰기 수정하기 프론트 수정완료
refactor : 면접후기 게시판 글쓰기 수정하기 프론트 수정완료
Close #{이슈_번호}
=> refactor : 면접후기 게시판 글쓰기 수정하기 프론트 수정완료

Team_Project/src/main/resources/static/style/login.css, Team_Project/src/main/resources/static/style/main.css, Team_Project/src/main/webapp/WEB-INF/views/common/nav.jsp, Team_Project/src/main/webapp/WEB-INF/views/common/nav_main.jsp, Team_Project/src/main/webapp/WEB-INF/views/member/join_com.jsp, Team_Project/src/main/webapp/WEB-INF/views/member/join_indv.jsp, Team_Project/src/main/webapp/WEB-INF/views/security/userLogin.jsp
페이지 스타일 수정
<br/>
Close #{이슈_번호}
=> chore: 페이지 스타일 수정

Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp
멘토모드 프론트 1차 업데이트
<br/>
Close #{이슈_번호}
=> 멘토모드 프론트 1차 업데이트

Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp
mentor.jsp 프론트 2차 업데이트
<br/>
Close #{이슈_번호}
=> mentor.jsp 프론트 2차 업데이트

Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp, Team_Project/src/main/webapp/WEB-INF/views/recruit/template.jsp
metor_form footer안나옴 ㅠ
<br/>
Close #{이슈_번호}
=> metor_form footer안나옴 ㅠ

Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp
mentor_form 프론트 1차 업데이트
footer 안나옴 ㅠㅠ 
<br/>
Close #{이슈_번호}
=> mentor_form 프론트 1차 업데이트

Team_Project/src/main/webapp/WEB-INF/views/interview/mentor_form.jsp
MENTOR_FORM UPDATE
푸터안나옴 
<br/>
Close #{이슈_번호}
=> MENTOR_FORM UPDATE

Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp
total.jsp remove
<br/>
Close #{이슈_번호}
=> total.jsp remove

Team_Project/src/main/webapp/WEB-INF/views/interview/backEnd.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/customMode.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/frontEnd.jsp
interview last page update
interview last page update
<br/>
Close #{이슈_번호}
=> interview last page update

Team_Project/src/main/webapp/WEB-INF/views/interview/main.jsp
인터뷰 메인 문구수정
<br/>
Close #{이슈_번호}
=> chore: 인터뷰 메인 문구수정

Team_Project/src/main/java/com/team/interview/controller/ReviewController.java, Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java, Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
fix : 대댓글 기능 통합버전 이메일 오류 코드 수정
fix : 대댓글 기능 통합버전 이메일 오류 코드 수정
Close #{이슈_번호}
=> fix : 대댓글 기능 통합버전 이메일 오류 코드 수정

Team_Project/src/main/java/com/team/interview/controller/BoardController.java, Team_Project/src/main/java/com/team/interview/service/AllServiceImpl.java, Team_Project/src/main/resources/mybatis/mappers/question.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/total_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/interview/custom.jsp, Team_Project/src/main/webapp/WEB-INF/views/recruit/template.jsp
allQlist update
<br/>
Close #{이슈_번호}
=> allQlist update

Team_Project/build.gradle, Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/resources/application.properties, Team_Project/src/main/resources/mybatis/mappers/answer.xml, Team_Project/src/main/webapp/WEB-INF/views/board/total_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/recruit/template.jsp
멘토 등록 완료 페이지 수정
<br/>
Close #{이슈_번호}
=> 멘토 등록 완료 페이지 수정

Team_Project/src/main/resources/mybatis/mappers/mentormode.xml
mentor면접 목록 정렬 변경
<br/>
Close #{이슈_번호}
=> mentor면접 목록 정렬 변경

Team_Project/src/main/java/com/team/interview/controller/InterviewController.java, Team_Project/src/main/java/com/team/interview/service/MemberService.java, Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java, Team_Project/src/main/java/com/team/interview/service/ProfileServiceImpl.java, Team_Project/src/main/webapp/WEB-INF/views/interview/mentor.jsp
멘토모드 update
<br/>
Close #{이슈_번호}
=> 멘토모드 update

Team_Project/src/main/webapp/WEB-INF/views/board/total.jsp
total.jsp update
<br/>
Close #{이슈_번호}
=> total.jsp update

Team_Project/src/main/webapp/WEB-INF/views/board/total_detail.jsp
total_detail.jsp 1차 프론트 update
<br/>
Close #{이슈_번호}
=> total_detail.jsp 1차 프론트 update

Team_Project/src/main/webapp/WEB-INF/views/common/footer.jsp
footer.jsp update
<br/>
Close #{이슈_번호}
=> footer.jsp update

Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp, Team_Project/src/main/webapp/WEB-INF/views/common/nav.jsp, Team_Project/src/main/webapp/WEB-INF/views/common/nav_main.jsp, Team_Project/src/main/webapp/WEB-INF/views/contact.jsp, Team_Project/src/main/webapp/WEB-INF/views/main.jsp
last update
<br/>
Close #{이슈_번호}
=> last update

Team_Project/src/main/webapp/WEB-INF/views/main.jsp
AngryPig_last_update
<br/>
Close #{이슈_번호}
=> AngryPig_last_update

Team_Project/src/main/resources/static/style/total_detail_comment.css, Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp, Team_Project/src/main/webapp/WEB-INF/views/board/total_detail2.jsp
refactor: total_detail 프론트 코드 수정
refactor: total_detail 프론트 코드 수정
Close #{이슈_번호}
=> refactor: total_detail 프론트 코드 수정

Team_Project/src/main/resources/static/js/board_detail.js, Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
feat: 대댓글 수정삭제 권한부여
feat: 대댓글 수정삭제 권한부여
Close #{이슈_번호}
=> feat: 대댓글 수정삭제 권한부여
